version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: yourusername
      DB_PASSWORD: yourpassword
      DB_NAME: yourdbname
    depends_on:
      - db

volumes:
  postgres_data:
